version: '3'
services:

  ruuvijava:
    # See Dockerfile
    image: ruuvi-collector:latest
    container_name: ruuvijava
    restart: unless-stopped

    # Docker needs net admin capabilities to access ble in privileged
    # mode. See: https://man7.org/linux/man-pages/man7/capabilities.7.html
    cap_add:
        -   NET_ADMIN
    # ..and network mode needs to be host, to see why
    # ..see: https://github.com/lxc/lxd/issues/3265#issuecomment-299439027
    network_mode: host

    volumes:
        # copy the configuration to container root
        - ./configuration.yml:/configuration.yml

